In [2]:
# ==========================================================
# Project: Auto Tagging Support Tickets Using LLM
# Objective:
# Automatically classify support tickets into relevant
# categories using Zero-Shot and Prompt-Engineered approaches.
#
# Model Used:
# facebook/bart-large-mnli (Zero-Shot Classification Model)
#
# The system outputs Top 3 predicted tags with confidence scores.
# Performance is evaluated using accuracy metric.
# ==========================================================
# Install required libraries
!pip install transformers
!pip install torch
!pip install pandas
!pip install scikit-learn

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.0.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers) (3.24.3)
Requirement already satisfied: huggingface-hub<2.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (1.5.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (1.3.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.28.1)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.24.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (4.15.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (0.16.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (0.1.2)
Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (2.10.0+cpu)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch) (3.24.3)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch) (2025.3.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch) (3.0.3)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (2.0.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)

In [3]:
#Importing Libraries
import pandas as pd
import numpy as np
from transformers import pipeline
from sklearn.metrics import accuracy_score

In [4]:
#Load Zero-Shot Model
classifier = pipeline(
    "zero-shot-classification",
    model="facebook/bart-large-mnli"
)
# ----------------------------------------------------------
# Load Zero-Shot Classification Model
# ----------------------------------------------------------
# We use facebook/bart-large-mnli which is trained on
# Natural Language Inference (NLI).
# It allows us to classify text into categories without
# training on our specific dataset (Zero-Shot Learning).
# ----------------------------------------------------------

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/1.63G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/515 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

In [ ]:
#Create Dataset
data = {
    "ticket": [
        "I cannot log into my account",
        "Payment was deducted but order not confirmed",
        "App crashes when I open settings",
        "How can I reset my password?",
        "The website is very slow today",
        "I want to cancel my subscription",
        "Refund has not been processed yet"
    ]
}

df = pd.DataFrame(data)
df

                                         ticket
0                  I cannot log into my account
1  Payment was deducted but order not confirmed
2              App crashes when I open settings
3                  How can I reset my password?
4                The website is very slow today
5              I want to cancel my subscription
6             Refund has not been processed yet

In [ ]:
#Define Candidate Labels
candidate_labels = [
    "Login Issue",
    "Payment Problem",
    "Technical Bug",
    "Account Management",
    "Performance Issue",
    "Subscription",
    "Refund"
]

In [ ]:
# ----------------------------------------------------------
# ZERO-SHOT CLASSIFICATION
# ----------------------------------------------------------
# For each support ticket:
# 1. The model compares the ticket text with candidate labels.
# 2. It assigns probability scores to each label.
# 3. We extract the Top 3 most probable labels.
#
# This approach does not require any additional training.
# ----------------------------------------------------------
results = []

for ticket in df["ticket"]:
    output = classifier(ticket, candidate_labels)

    # Extract Top 3 Tags
    top_3 = list(zip(output["labels"][:3], output["scores"][:3]))

#Create Results DataFrame
    results.append({
        "Ticket": ticket,
        "Top 1 Tag": top_3[0][0],
        "Top 1 Score": top_3[0][1],
        "Top 2 Tag": top_3[1][0],
        "Top 2 Score": top_3[1][1],
        "Top 3 Tag": top_3[2][0],
        "Top 3 Score": top_3[2][1]
    })

results_df = pd.DataFrame(results)
results_df

,Ticket,Top 1 Tag,Top 1 Score,Top 2 Tag,Top 2 Score,Top 3 Tag,Top 3 Score
0,I cannot log into my account,Login Issue,0.769011,Subscription,0.071466,Performance Issue,0.049645
1,Payment was deducted but order not confirmed,Payment Problem,0.494222,Performance Issue,0.129768,Account Management,0.122913
2,App crashes when I open settings,Performance Issue,0.576157,Technical Bug,0.158691,Login Issue,0.111890
3,How can I reset my password?,Login Issue,0.487662,Account Management,0.201227,Subscription,0.093433
4,The website is very slow today,Performance Issue,0.714518,Technical Bug,0.065745,Subscription,0.062441
5,I want to cancel my subscription,Subscription,0.609616,Refund,0.175178,Payment Problem,0.074870
6,Refund has not been processed yet,Refund,0.630402,Payment Problem,0.179828,Subscription,0.052611

In [ ]:
#Add True Labels
true_labels = [
    "Login Issue",
    "Payment Problem",
    "Technical Bug",
    "Account Management",
    "Performance Issue",
    "Subscription",
    "Refund"
]

df["True Label"] = true_labels
df

                                         ticket          True Label
0                  I cannot log into my account         Login Issue
1  Payment was deducted but order not confirmed     Payment Problem
2              App crashes when I open settings       Technical Bug
3                  How can I reset my password?  Account Management
4                The website is very slow today   Performance Issue
5              I want to cancel my subscription        Subscription
6             Refund has not been processed yet              Refund

In [ ]:
predicted_labels = results_df["Top 1 Tag"]

df["Predicted Label"] = predicted_labels
df

,ticket,True Label,Predicted Label
0,I cannot log into my account,Login Issue,Login Issue
1,Payment was deducted but order not confirmed,Payment Problem,Payment Problem
2,App crashes when I open settings,Technical Bug,Performance Issue
3,How can I reset my password?,Account Management,Login Issue
4,The website is very slow today,Performance Issue,Performance Issue
5,I want to cancel my subscription,Subscription,Subscription
6,Refund has not been processed yet,Refund,Refund

In [ ]:
#Calculate Zero-Shot Accuracy
accuracy = accuracy_score(df["True Label"], df["Predicted Label"])
print("Zero-Shot Accuracy:", accuracy)
# from output we can predict  model correctly predicted 5 out of 7 tickets.

Zero-Shot Accuracy: 0.7142857142857143

In [ ]:
#Enhanced Labels
#Here we improved labels by adding descriptions.
enhanced_labels = [
    "Login Issue: problems related to login, authentication, password errors, unable to access account",

    "Payment Problem: issues with payment failure, money deducted, transaction errors",

    "Technical Bug: app crashes, software bugs, unexpected errors, system malfunction",

    "Account Management: updating profile, changing account settings, password reset",

    "Performance Issue: slow website, lagging app, loading problems",

    "Subscription: cancelling or modifying subscription plans",

    "Refund: refund requests, money not returned, reimbursement issues"
]

In [ ]:
# Run Classification Again
few_shot_results = []

for ticket in df["ticket"]:
    output = classifier(ticket, enhanced_labels)

    top_3 = list(zip(output["labels"][:3], output["scores"][:3]))

    few_shot_results.append({
        "Ticket": ticket,
        "Top 1 Tag": top_3[0][0],
        "Top 2 Tag": top_3[1][0],
        "Top 3 Tag": top_3[2][0]
    })

few_shot_df = pd.DataFrame(few_shot_results)
few_shot_df

,Ticket,Top 1 Tag,Top 2 Tag,Top 3 Tag
0,I cannot log into my account,"Login Issue: problems related to login, authen...","Payment Problem: issues with payment failure, ...","Technical Bug: app crashes, software bugs, une..."
1,Payment was deducted but order not confirmed,"Payment Problem: issues with payment failure, ...","Refund: refund requests, money not returned, r...",Subscription: cancelling or modifying subscrip...
2,App crashes when I open settings,"Technical Bug: app crashes, software bugs, une...","Performance Issue: slow website, lagging app, ...","Payment Problem: issues with payment failure, ..."
3,How can I reset my password?,"Login Issue: problems related to login, authen...","Account Management: updating profile, changing...",Subscription: cancelling or modifying subscrip...
4,The website is very slow today,"Performance Issue: slow website, lagging app, ...","Technical Bug: app crashes, software bugs, une...","Login Issue: problems related to login, authen..."
5,I want to cancel my subscription,Subscription: cancelling or modifying subscrip...,"Refund: refund requests, money not returned, r...","Login Issue: problems related to login, authen..."
6,Refund has not been processed yet,"Refund: refund requests, money not returned, r...","Payment Problem: issues with payment failure, ...",Subscription: cancelling or modifying subscrip...

In [ ]:
#Remove Description
few_shot_df["Top 1 Tag"] = few_shot_df["Top 1 Tag"].apply(lambda x: x.split(":")[0])
few_shot_df

,Ticket,Top 1 Tag,Top 2 Tag,Top 3 Tag
0,I cannot log into my account,Login Issue,"Payment Problem: issues with payment failure, ...","Technical Bug: app crashes, software bugs, une..."
1,Payment was deducted but order not confirmed,Payment Problem,"Refund: refund requests, money not returned, r...",Subscription: cancelling or modifying subscrip...
2,App crashes when I open settings,Technical Bug,"Performance Issue: slow website, lagging app, ...","Payment Problem: issues with payment failure, ..."
3,How can I reset my password?,Login Issue,"Account Management: updating profile, changing...",Subscription: cancelling or modifying subscrip...
4,The website is very slow today,Performance Issue,"Technical Bug: app crashes, software bugs, une...","Login Issue: problems related to login, authen..."
5,I want to cancel my subscription,Subscription,"Refund: refund requests, money not returned, r...","Login Issue: problems related to login, authen..."
6,Refund has not been processed yet,Refund,"Payment Problem: issues with payment failure, ...",Subscription: cancelling or modifying subscrip...

In [ ]:
#Few-Shot Accuracy
# Now 6 out of 7 correct.
few_shot_accuracy = accuracy_score(df["True Label"], few_shot_df["Top 1 Tag"])
print("Few-Shot Accuracy:", few_shot_accuracy)

Few-Shot Accuracy: 0.8571428571428571

In [ ]:
comparison = pd.DataFrame({
    "Method": ["Zero-Shot", "Few-Shot (Prompt Engineered)"],
    "Accuracy": [accuracy, few_shot_accuracy]
})

comparison
#So accuracy improved by 14%.

#That clearly shows:

#Prompt engineering improves classification performance.

                         Method  Accuracy
0                     Zero-Shot  0.714286
1  Few-Shot (Prompt Engineered)  0.857143

In [ ]:
improvement = few_shot_accuracy - accuracy
print("Accuracy Improvement:", improvement)
#So accuracy improved by 14%.

#That clearly shows:

#Prompt engineering improves classification performance.

Accuracy Improvement: 0.1428571428571428